Algoritmo "Básico"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/02/2023
Var
// Seção de Declarações das variáveis
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
i <- 1
repita

   escreval("Hello world!")
   i <- 1 + 1
ate i > 100

Fimalgoritmo